resources:
- manifests.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml

patchesStrategicMerge:
  - |-
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    metadata:
      name: validating-webhook-configuration
    webhooks:
      - name: vpoisonpillconfig.kb.io
        rules:
        - apiGroups:
          - poison-pill.medik8s.io
          apiVersions:
          - v1alpha1
          operations:
          - UPDATE
          resources:
          - poisonpillconfigs
        timeoutSeconds: 30
