
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-poison-pill-medik8s-io-v1alpha1-poisonpillconfig
  failurePolicy: Fail
  name: vpoisonpillconfig.kb.io
  rules:
  - apiGroups:
    - poison-pill.medik8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - poisonpillconfigs
  sideEffects: None
