# permissions for end users to view poisonpillremediationtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: poisonpillremediationtemplate-viewer-role
rules:
- apiGroups:
  - poison-pill.medik8s.io
  resources:
  - poisonpillremediationtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - poison-pill.medik8s.io
  resources:
  - poisonpillremediationtemplates/status
  verbs:
  - get
