# permissions for end users to view poisonpillremediations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: poisonpillremediation-viewer-role
rules:
- apiGroups:
  - poison-pill.medik8s.io
  resources:
  - poisonpillremediations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - poison-pill.medik8s.io
  resources:
  - poisonpillremediations/status
  verbs:
  - get
