# permissions for end users to edit poisonpillconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: poisonpillconfig-editor-role
rules:
- apiGroups:
  - poison-pill.medik8s.io
  resources:
  - poisonpillconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - poison-pill.medik8s.io
  resources:
  - poisonpillconfigs/status
  verbs:
  - get
