
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.openshift.io
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.openshift.io
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - poison-pill.medik8s.io
  resources:
  - poisonpillconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - poison-pill.medik8s.io
  resources:
  - poisonpillconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - poison-pill.medik8s.io
  resources:
  - poisonpillconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - poison-pill.medik8s.io
  resources:
  - poisonpillremediations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - poison-pill.medik8s.io
  resources:
  - poisonpillremediations/finalizers
  verbs:
  - update
- apiGroups:
  - poison-pill.medik8s.io
  resources:
  - poisonpillremediations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
