name: Publish Container Images
on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push a container image to quay.io/medik8s
    runs-on: ubuntu-20.04
    env:
      IMG: quay.io/medik8s/poison-pill-operator:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Quay.io
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io

      - name: Prepare Container Image
        run: make docker-build

      - name: Push to Quay.io
        run: make docker-push
