name: Go
on:
  push:
    branches:
      - master
      - release-*
  pull_request:
    branches:
      - master
      - release-*
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build and test
      run: make manifests generate docker-build

    - name: TestMutations
      run: make test-mutation-ci

